#FROM itsafeaturemythic/mythic_python_base:latest

#RUN pip3 install sanic==21.6
#RUN pip3 install requests

#WORKDIR /Mythic/

#CMD ["python3", "main.py"]

FROM ghcr.io/mythicc2profiles/dynamichttp:v0.0.1